name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile and Run all C programs in programs/
        run: |
          # Enable recursive globbing
          shopt -s globstar

          cd programs

          # Check if any .c files exist under this folder
          if ! ls **/*.c 1> /dev/null 2>&1; then
            echo "No .c files found in 'programs'. Skipping."
            exit 0
          fi

          # Loop through each .c file
          for c_file in **/*.c; do
            # Create a unique executable name from the relative path
            executable_name=$(echo "$c_file" | sed 's|/|_|g; s|\.c$||')_exec

            echo "---"
            echo "Compiling: $c_file"
            gcc "$c_file" -o "$executable_name"

            echo "Running: ./${executable_name}"
            ./"$executable_name"
            echo "---"
          done
