name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # Replace with your Python version (e.g., '3.10')

    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint and syntax check
      run: python -m py_compile $(find . -name "*.py")

    - name: Run tests
      run: |
        if [ -d tests ]; then pytest; else echo "No tests found"; fi
